### ISSUE TITLE
#TK Diseñar la interfaz de usuario (UI) y la experiencia de usuario (UX).

### ISSUE THREAD

**Issue by CaronlineArg** [FrancoGL/ISPC-Mobile#16]
-UI intuitiva y atractiva
-Crear kits reutilizables
-Crear los bloques: átomos y moléculas

**Comment by Sole1988** [comment]
Enlace a Figma: 
https://www.figma.com/file/hDZKRtDLs86LMZCJbqkNIY/ISPC-MOBILE?type=design&node-id=0-1&mode=design&t=3d7ApHxSl7HGvGhk-0
