### ISSUE TITLE
#TK Integar un sistema de pago seguro para la tienda en línea.

### ISSUE THREAD

**Issue by CaronlineArg** [FrancoGL/ISPC-Mobile#24]

**Comment by Noobuyer** [comment]
intente subirlo a develop, pero no marca el pr, procedo a probar stripe- (aunque creo que si luego vamos a sacar el carrito, no tiene mucho sentido) / debo afirmar que desconozco como implementar sobre la interfaz una interfaz para pagos...

**Comment by Noobuyer** [comment]
intente implementar stripe y google pay, pero opte por dejarlo sin ambos-

**Comment by Noobuyer** [comment]
se corregirá la funcionalidad e intentara implementar ambos métodos de pago
