### ISSUE TITLE
#US8 Como usuario, quiero acceder a rutinas de entrenamiento específicas.

### ISSUE THREAD

**Issue by CaronlineArg** [FrancoGL/ISPC-Mobile#30]
- [x] #84
- [x] #19 
- [x] #22

**Comment by FrancoGL** [comment]
@federico42o Una consulta, las rutinas son la pestaña de ejercicios? es decir, al hacer clic en un ejercicio, se mostrará indo del mismo y dará la opción de la cantidad de repeticiones, minutos, etc. O nada que ver? xD

**Comment by federico42o** [comment]
@FrancoGL por lo que entendi, hay ejercicios que son un contenido separado, y despues con esos ejercicios se puede conformar una rutina, que ahi si seria repeticiones de x ejercicio etc

**Comment by federico42o** [comment]
@FrancoGL viendo el figma creo que son lo mismo xd, mira https://www.figma.com/file/hDZKRtDLs86LMZCJbqkNIY/ISPC-MOBILE?type=design&node-id=0-1&mode=design&t=yvLpTfH226Rpb3uN-0

**Comment by FrancoGL** [comment]
@federico42o si, parecen lo mismo xd
