### ISSUE TITLE
#REQF Visualización de rutinas de entrenamiento con descripciones y ejercicios.

### ISSUE THREAD

**Issue by CaronlineArg** [FrancoGL/ISPC-Mobile#41]

**Comment by FrancoGL** [comment]
@federico42o y esto como sería? lo mismo que el activity de descripción de los ejercicios?

**Comment by federico42o** [comment]
@FrancoGL si es lo mismo,  como lo vi acá lo asigne para q no quede colgado y cuando lo termines lo cerras
