### ISSUE TITLE
#REQF Generación de planes de entrenamiento personalizados.

### ISSUE THREAD

**Issue by CaronlineArg** [FrancoGL/ISPC-Mobile#42]

**Comment by Noobuyer** [comment]
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;

public class PlanEntrenamientoActivity extends AppCompatActivity {
    private EditText edadEditText;
    private EditText nivelCondicionEditText;
    private EditText objetivoEditText;
    private Button generarPlanButton;
    private TextView resultadoTextView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_plan_entrenamiento);

        edadEditText = findViewById(R.id.edadEditText);
        nivelCondicionEditText = findViewById(R.id.nivelCondicionEditText);
        objetivoEditText = findViewById(R.id.objetivoEditText);
        generarPlanButton = findViewById(R.id.generarPlanButton);
        resultadoTextView = findViewById(R.id.resultadoTextView);

        generarPlanButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                generarPlanEntrenamiento();
            }
        });
    }

    private void generarPlanEntrenamiento() {
        // Obtiene la información del usuario
        int edad = Integer.parseInt(edadEditText.getText().toString());
        String nivelCondicion = nivelCondicionEditText.getText().toString();
        String objetivo = objetivoEditText.getText().toString();

        // Realiza la lógica para generar un plan de entrenamiento personalizado
        String planEntrenamiento = generarPlan(edad, nivelCondicion, objetivo);

        // Muestra el plan de entrenamiento en el TextView
        resultadoTextView.setText(planEntrenamiento);
    }

    private String generarPlan(int edad, String nivelCondicion, String objetivo) {
        // Aquí implementa la lógica para generar un plan de entrenamiento personalizado
        // Esto puede implicar cálculos basados en la información proporcionada por el usuario
        // y la selección de ejercicios adecuados, duraciones, intensidades, etc.

        // Por ejemplo, podrías tener una base de datos de ejercicios y seleccionar ejercicios
        // basados en los objetivos y el nivel de condición física del usuario.

        // Devuelve un plan de entrenamiento generado
        return "Plan de entrenamiento personalizado:\n" +
               "Día 1: Ejercicio 1, Ejercicio 2, Descanso\n" +
               "Día 2: Ejercicio 3, Ejercicio 4, Descanso\n" +
               "Día 3: Ejercicio 5, Ejercicio 6, Descanso\n" +
               // ... continúa con más días y ejercicios ...
               "Día N: Ejercicio N, Descanso";
    }
}
