### ISSUE TITLE
#US como usuario quiero poder visualizar pantallas sobre planes de alimentacion

### ISSUE THREAD

**Issue by sofgln** [FrancoGL/ISPC-Mobile#80]
Plantilla historia de usuario / Como ..., quiero ..., para ....

🚀 ACCIÓN

Como usuario registrado en un sitio web de comercio electrónico, quiero tener la opción de guardar productos en una lista de deseos, para poder revisarlos más tarde y considerar la compra.

⛳ ALCANCE

QA deberá validar que los usuarios registrados pueden agregar productos a su lista de deseos y luego eliminarlos si lo desean. También deben asegurarse de que la lista de deseos esté disponible para su revisión posterior.

🏴‍☠️ FUERA DE ALCANCE

N/A

✅ CRITERIOS DE ACEPTACIÓN

#ESCENARIO 1 (Maximizar)

Scenario: Agregar un producto a la lista de deseos
Given que estoy registrado y he iniciado sesión
Y estoy viendo un producto que me interesa
Cuando hago clic en el botón "Agregar a la lista de deseos"
Entonces el producto se agrega con éxito a mi lista de deseos

#ESCENARIO 2 (Minimizar)

Scenario: Eliminar un producto de la lista de deseos
Given que estoy registrado y he iniciado sesión
Y tengo un producto en mi lista de deseos
Cuando hago clic en el botón "Eliminar de la lista de deseos"
Entonces el producto se elimina con éxito de mi lista de deseos

🧩 CONTEXTO

Esta funcionalidad permitirá a los usuarios guardar productos que les interesen y acceder a ellos fácilmente más tarde, lo que mejorará la experiencia de compra en nuestro sitio web.

**Comment by Noobuyer** [comment]
Actualizado, a revisar
